/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../components/AppButton.vue')['default']
    AppInput: typeof import('./../components/AppInput.vue')['default']
    AppModal: typeof import('./../components/AppModal.vue')['default']
    DataTable: typeof import('./../components/DataTable.vue')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideLanguages: typeof import('~icons/lucide/languages')['default']
    IconLucideLogOut: typeof import('~icons/lucide/log-out')['default']
    IconLucideMaximize: typeof import('~icons/lucide/maximize')['default']
    IconLucideMinimize: typeof import('~icons/lucide/minimize')['default']
    IconLucidePalette: typeof import('~icons/lucide/palette')['default']
    IconLucidePanelLeftClose: typeof import('~icons/lucide/panel-left-close')['default']
    IconLucidePanelLeftOpen: typeof import('~icons/lucide/panel-left-open')['default']
    IconLucideSettings: typeof import('~icons/lucide/settings')['default']
    IconLucideX: typeof import('~icons/lucide/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
