/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppModal: typeof import('./../components/AppModal.vue')['default']
    DataTable: typeof import('./../components/DataTable.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideLayoutDashboard: typeof import('~icons/lucide/layout-dashboard')['default']
    IconLucidePanelLeftClose: typeof import('~icons/lucide/panel-left-close')['default']
    IconLucidePanelLeftOpen: typeof import('~icons/lucide/panel-left-open')['default']
    IconLucideSettings: typeof import('~icons/lucide/settings')['default']
    IconLucideX: typeof import('~icons/lucide/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
